### ISSUE TITLE
Delay and wait character do not seem to do anything

### ISSUE THREAD

**Issue by xeroxoid** [candlefinance/haptics#2]
Hi, great lib.

I think delays using the `-` character are not recognised, neither does the delay time (second argument) seem to have any effect (tried `1.0`)

so the following pattern just seems like one continuous haptic feedback with no pauses:

```javascript
    // pattern, delay
    hapticWithPattern(
      ['.', '.', '.', 'o', 'O', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'O', 'o', '.', '.', '.', '.'],
      1.0,
    );
```

**Comment by gtokman** [comment]
Thanks @xeroxoid! & yes I did notice this too. 

I'll take a look and see if I can push a fix by this weekend.

**Comment by gtokman** [comment]
@xeroxoid fixed in the lastest release!

**Comment by xeroxoid** [comment]
Amazing, thanks!
